language: objective-c
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - sudo mkdir -p ~/Library/RubyMotion/build
    - sudo chown -R travis ~/Library/RubyMotion/build
    - sudo motion update
